---
title: "Dtrackr - Consort statement example"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Dtrackr - Consort statement example}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
bibliography: dtrackr.bib
csl: dtrackr.csl
---

# Consort statement

TODO: some background as to why.
Cite data sets [@ramanaCriticalComparativeStudy; @ramanaCriticalStudySelected2011; @Dua:2019]

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)

options(warn=1)
```

```{r setup}
library(tidyverse)
library(dtrackr)

```

```{r}
ilpd = dtrackr::ILPD %>% 
  track() %>%
  include_any(
    Gender == "Female" & Total_Bilirubin >= 0.7 ~ "{.included} women with bili>0.7",
    Gender == "Male" & Total_Bilirubin >= 0.8 ~ "{.included} men with bili>0.8"
  ) %>%
  group_by(Case_or_Control, .messages="cases versus controls", .add=TRUE) %>%
  comment(.headline = "{Case_or_Control}", .messages = "{.count}") %>%
  exclude_all(
    Age<18 ~ "{.excluded} subjects under 18",
    Age>80 ~ "{.excluded} subjects over 80",
    .headline = NULL
  ) %>%
  comment(.headline = "{Case_or_Control}", .messages = "{.count} after exclusions") %>%
  status(
    mean_bili = sprintf("%1.2f \u00B1 %1.2f",mean(Total_Bilirubin),sd(Total_Protein)),
    mean_alb = sprintf("%1.2f \u00B1 %1.2f",mean(Albumin),sd(Albumin)),
    .headline = "{Case_or_Control}",
    .messages = c(
      "bilirubin: {mean_bili}",
      "albumin: {mean_alb}"
    )                    
  ) %>%
  ungroup(.messages = "{.count} in final data set")

ilpd %>% flowchart()

```

# References

```{r}
devtools::load_all()
library(dtrackr)

excl = exclusions_collector("default stage description: invocation {index}")

excl$reset()

iris %>%
  track() %>% 
  exclude_all(
    Petal.Length > 5.8 ~ "{.excluded} long ones",
    Petal.Length < 1.3 ~ "{.excluded} short ones",
    .exclusionHandler = excl$accumulate("overridden stage description: invocation {index}")
  ) %>%
  comment("leaving {.count}") %>%
  exclude_all(
    Petal.Width < 0.2 ~ "{.excluded} narrow ones",
    Petal.Width > 2.1 ~ "{.excluded} wide ones",
    .exclusionHandler = excl$accumulate()
  ) %>% 
  comment("leaving {.count}") %>%
  flowchart()

```

```{r}
excl$collect()
```

<div id="refs"></div>
